<?php 

/**
* további infók a form alterről, http://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_form_alter/7
*/

function formolok_form_user_login_alter(&$form, &$form_state) {  
  // Submit elem értékének átírása
  $form['actions']['submit']['#value'] = 'Go, Go, Gooo';
  
  // Submit elem súlyának módosítsa
  $form['actions']['#weight'] = -1;
  
  // Usernév elem súlyának módosítása 
  $form['name']['#weight'] = 0;
  
  // Usernév elem súlyának módosítása 
  $form['pass']['#weight'] = -2;
  
  // saját szöveg elhelyezése a formban
}
