<?php 

/**
 * Kapcsold be a Devel modult, és ezzel megkaphatod mik a formok id-jai a látogatott oldalon. 
 * Ha használni szeretnéd, kapcsold be a devel modult és kommenteld ki a következő dpm-et. 
 */

function formolok_form_alter(&$form, &$form_state, $form_id) {
  // dpm($form_id);
}
// A drupal oldalad /user oldalon található formjának módosítása
function formolok_form_user_login_alter(&$form, &$form_state) {  
  // Submit elem értékének átírása
  $form['actions']['submit']['#value'] = 'Go, Go, Gooo'; 
  // Submit elem súlyának módosítsa
  $form['actions']['#weight'] = -1;
  // Usernév elem súlyának módosítása 
  $form['name']['#weight'] = 0;
  // Usernév elem súlyának módosítása 
  $form['pass']['#weight'] = -2;
}

/**
* további infók a form alterről, goo.gl/CG2dw
*/